GET http://localhost:8080/

###
GET http://localhost:8080/api

###
GET http://localhost:8080/api/user

###
POST http://localhost:8080/api/user/signin
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###
POST http://localhost:8080/api/user/signup