version: '3.8'

services:
  web:
    build: .
    environment:
      - MYSQL_HOST=db
    depends_on:
      - db
    restart: always
    ports:
      - 8000:8000
  db:
    build: ./mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: cms