export const COMPLAINT_STATES = {
    DRAFT: "D",
    PENDING_DIS_BEFORE: "P-DIS-B",
    PENDING_DIV_BEFORE: "P-DIV-B",
    IN_PROGRESS: "IP",
    PENDING_DIV_AFTER: "P-DIV-A",
    PENDING_DIS_AFTER: "P-DIS-A",
    SOLVED: "S",
    REJECTED: "R"
}